question_data = [
    {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
     "question": "A person can get sunburned on a cloudy day.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "The Great Wall of China is visible from the moon.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Celebrities", "type": "boolean", "difficulty": "medium",
     "question": "Michael Jackson had a pet python named Crusher;.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "Manchester United won the 2013-14 English Premier League.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "The cover of The Beatles album &quot;Abbey Road&quot; featured a Volkswagen Beetle in the background.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy", "question": "Vatican City is a country.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "hard",
     "question": "The Kingdom of Prussia briefly held land in Estonia.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
     "question": "Unturned originally started as a Roblox game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The vapor produced by e-cigarettes is actually water.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Norwegian producer Kygo released a remix of the song &quot;Sexual Healing&quot; by Marvin Gaye.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "Sargon II, a king of the Neo-Assyrian Empire, was a direct descendant of Sargon of Akkad.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "Assyrian king Sennacherib&#039;s destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
     "question": "111,111,111 x 111,111,111 = 12,345,678,987,654,321", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The game &quot;Battlefield 1&quot; takes place during World War I.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "No Game No Life first aired in 2014.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In the &quot;Half-Life&quot; series, &quot;H.E.V&quot; stands for &quot;Hazardous Evasiveness Vest&quot;",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "medium",
     "question": "In the webcomic Homestuck, the first character introduced is Dave Strider.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "easy",
     "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
     "question": "The song &quot;Mystery Train&quot; was released by artist &quot;Little Junior&#039;s Blue Flames&quot; in 1953.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
     "question": "The chemical element Lithium is named after the country of Lithuania.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
     "question": "Bob Ross was a US Air Force pilot.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Watch_Dogs 2 is a prequel.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "medium",
     "question": "The Roman god &quot;Jupiter&quot; was first known as &quot;Zeus&quot; to the Greeks.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "medium",
     "question": "&quot;Rich Uncle Pennybags&quot; from the board game &quot;Monopoly&quot; wears a monocle.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Politics", "type": "boolean", "difficulty": "medium",
     "question": "Helen Clark was the 37th Prime Minister of Australia.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
     "question": "The majority of Subaru vehicles are made in China.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "The scrapped Sonic the Hedgehog 2 level &quot;Hidden Palace Zone&quot; was later reused in the iOS port of the game. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Green Eggs and Ham&quot; consists of only 50 different words.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "medium",
     "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
     "question": "Nutcracker Suite was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
     "question": "An isosceles triangle has two sides of equal length as opposed to three.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "A pasodoble is a type of Italian pasta sauce.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Vehicles", "type": "boolean", "difficulty": "hard",
     "question": "The term &quot;GTO&quot; was originated by Ferrari?", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
     "question": "The video game &quot;Fuel&quot; has an open world that is 5,560 square miles?",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Art", "type": "boolean", "difficulty": "hard",
     "question": "The Statue of Liberty&#039;s official name is &ldquo;Liberty Enlightening the World&rdquo;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
     "question": "The Harry Potter series of books, combined, are over 1,000,000 words in length.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
     "question": "Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The Lord of The Rings&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
]
